name: Github actions demo 
run-name: ${{ github.actor }} is testing out GitHub Actions 
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest 
    steps:
      - run: echo "github actions demo"
      - name: List all files in repository
        run: |
          ls ${{ github.workspace }}
